"""The policy-resolution generator must reproduce its committed vectors.

A committed vector nobody can regenerate is a number that cannot be checked. If
the generator and the files drift, the files win by default and the drift is
invisible, which is the failure agentrust-io/trace-spec#171 was written to
catch for that repository's ``examples/``.

trace-tests has no equivalent guard, and trace-tests PR #66 states the reason a
cross-repository one is not the answer: "a guard that needs another repository
checked out is a guard that gets skipped." This guard is therefore
self-contained — it imports the generator that sits beside the vectors and
regenerates into a temporary directory, comparing bytes.

Regenerating into ``tmp_path`` rather than in place is the load-bearing part.
Running the generator over its own directory and then comparing those files to
themselves agrees no matter what the generator does.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest

VECTOR_DIR = Path(__file__).parent / "vectors" / "policy-resolution"
GENERATOR = VECTOR_DIR / "gen_policy_resolution.py"


def _load_generator():
    spec = importlib.util.spec_from_file_location("gen_policy_resolution", GENERATOR)
    assert spec and spec.loader, "generator module could not be loaded"
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _committed_files() -> list[Path]:
    return sorted(p for p in VECTOR_DIR.rglob("*.json") if p.is_file())


@pytest.mark.level0
def test_the_generator_is_present_beside_the_vectors() -> None:
    """Self-containment: the guard must not need another repository."""
    assert GENERATOR.is_file(), (
        "gen_policy_resolution.py must sit in the vector directory, so the "
        "set can be regenerated by anyone holding only that directory"
    )


@pytest.mark.level0
def test_the_generator_reproduces_every_committed_file(tmp_path: Path) -> None:
    module = _load_generator()
    module.main(tmp_path)

    committed = _committed_files()
    assert committed, "no vectors found; the set is empty"

    mismatched: list[str] = []
    missing: list[str] = []
    for path in committed:
        rel = path.relative_to(VECTOR_DIR)
        produced = tmp_path / rel
        if not produced.is_file():
            missing.append(str(rel))
            continue
        if produced.read_bytes() != path.read_bytes():
            mismatched.append(str(rel))

    assert not missing, f"generator did not produce: {missing}"
    assert not mismatched, (
        f"generator output differs from the committed bytes: {mismatched}. "
        "Re-run tests/vectors/policy-resolution/gen_policy_resolution.py "
        "and commit the result, or fix the generator — but do not edit a vector "
        "by hand and leave the generator behind."
    )


@pytest.mark.level0
def test_the_generator_produces_nothing_the_set_does_not_carry(tmp_path: Path) -> None:
    """Both directions: a file the generator emits but nobody committed is drift too."""
    module = _load_generator()
    module.main(tmp_path)

    produced = {p.relative_to(tmp_path) for p in tmp_path.rglob("*.json") if p.is_file()}
    committed = {p.relative_to(VECTOR_DIR) for p in _committed_files()}
    assert produced == committed, (
        f"only generated: {sorted(str(p) for p in produced - committed)}; "
        f"only committed: {sorted(str(p) for p in committed - produced)}"
    )


@pytest.mark.level0
def test_the_committed_bytes_use_lf_and_ascii_only() -> None:
    """The two properties the digests depend on, asserted rather than assumed.

    CRLF translation changes every policy digest. ``.gitattributes`` in the
    vector directory pins ``eol=lf``; this fails loudly if that protection is
    ever removed. ASCII-only is separate: ``conftest.load_vector`` reads with
    ``Path.read_text()`` and no explicit encoding, so a non-ASCII byte would be
    decoded under the platform's locale.
    """
    for path in _committed_files():
        data = path.read_bytes()
        assert b"\r\n" not in data, f"{path.name} contains CRLF; digests will not match"
        assert all(b < 128 for b in data), f"{path.name} contains a non-ASCII byte"
